import CreatePostForm from '@/components/CreatePostForm';
import PostList from '@/components/PostList';
import { useAppSelector } from '@/redux/hooks';
import withAuth from '@/services/withAuth/withAuth';
import Head from 'next/head';

 function Home() {
  const { userData } = useAppSelector(state => state.user)

  return (
    <>
      <Head>
        <title>Home - CodeLeap Network</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main>
        <CreatePostForm />
        <PostList />
      </main>
    </>
  )
}

export default withAuth(Home)
