import { useAppSelector } from '@/redux/hooks';
import withAuth from '@/services/withAuth/withAuth';
import Head from 'next/head';

 function Home() {
  const { userData } = useAppSelector(state => state.user)

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        Test {userData.username}
      </main>
    </>
  )
}

export default withAuth(Home)
